### ISSUE TITLE
Issue with PHP Logger not found

### ISSUE THREAD

**Issue by joshelson** [marcelog/AsterTrace#1]
I am getting this error when running astertrace:

> php src/mg/AsterTrace/bin/astertrace.php ./conf
> PHP Fatal error:  Class 'Logger' not found in /usr/share/pear/Ding/Container/Impl/ContainerImpl.php on line 507

I did what I think was a fairly normal install of log4php, but to no avail.

Thanks in advance.

**Comment by marcelog** [comment]
Hi, thanks for your feedback!

You just need to have Logger.php (from log4php) in your classpath. Since you dont give any details about how the log4php installation was done, that's all I can say :)

Best,

**Comment by joshelson** [comment]
You are correct.  I did all the installs with pear, but the fix for me was to edit the include_path line in php.ini to

include_path = ".:/usr/share/pear/log4php:/usr/share/pear"

That seemed to resolve that particular issue.

**Comment by marcelog** [comment]
Excellent, glad to know that :) Don't hesitate to send any feedback (if got any) when you can try astertrace.

Regards :)

**Comment by software-pulse** [comment]
when executing PAMI in asterisk I am getting the below error...kindly check and give me suggestions

Warning: require_once(var/www/html/pami-1.72/PAMI-1.72/vendor/apache/log4php/src/main/php/Logger.php): failed to open stream: No such file or directory in /var/www/html/pami-1.72/PAMI-1.72/docs/examples/quickstart/test.php on line 20

Fatal error: require_once(): Failed opening required 'var/www/html/pami-1.72/PAMI-1.72/vendor/apache/log4php/src/main/php/Logger.php' (include_path='../../../src/mg:.:/usr/share/php:/usr/share/pear') in /var/www/html/pami-1.72/PAMI-1.72/docs/examples/quickstart/test.php on line 20

**Comment by alitariqmirza** [comment]
I am getting this error when running astertrace using following command:
**php src/mg/AsterTrace/bin/astertrace.php ./conf** 

PHP Fatal error:  Uncaught Error: Class 'Logger' not found in F:\xampp\htdocs\As
terTrace\AsterTrace\src\mg\Ding\Container\Impl\ContainerImpl.php:770
Stack trace:
#0 F:\xampp\htdocs\AsterTrace\AsterTrace\src\mg\AsterTrace\bin\astertrace.php(38
): Ding\Container\Impl\ContainerImpl::getInstance(Array)
#1 {main}
  thrown in F:\xampp\htdocs\AsterTrace\AsterTrace\src\mg\Ding\Container\Impl\Con
tainerImpl.php on line 770

Fatal error: Uncaught Error: Class 'Logger' not found in F:\xampp\htdocs\AsterTr
ace\AsterTrace\src\mg\Ding\Container\Impl\ContainerImpl.php:770
Stack trace:
#0 F:\xampp\htdocs\AsterTrace\AsterTrace\src\mg\AsterTrace\bin\astertrace.php(38
): Ding\Container\Impl\ContainerImpl::getInstance(Array)
#1 {main}
  thrown in F:\xampp\htdocs\AsterTrace\AsterTrace\src\mg\Ding\Container\Impl\Con
tainerImpl.php on line 770

please guide me what should i do to resolve this error. 
Thanks in advance.
