### ISSUE TITLE
astertrace.properties AMI username incorrect in default file

### ISSUE THREAD

**Issue by joshelson** [marcelog/AsterTrace#2]
The astertrace.properties for the AMI username contains a typo.

Line should read:

ami.username=

Rather than:

ami.user=

**Comment by marcelog** [comment]
Just commited the fix. Thanks for the report!

**Comment by marcelog** [comment]
This is not about this issue, but couldn't reach you by message (apparently there's no email associated with your github account). Just wanted to know if you had the change to try astertrace a little more and if it was any useful for you. Best!

**Comment by joshelson** [comment]
Just updated.  Feel free to email me.
